# see https://github.com/pmarsceill/just-the-docs/blob/master/_config.yml

title: "How-to-Guides"
description: A collection of bioinformatics focused How-to-Guides
remote_theme: pmarsceill/just-the-docs
color_scheme: biocommons

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/AustralianBioCommons/how-to-guides" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from

# Enable or disable heading anchors
heading_anchors: true

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"
